### ISSUE TITLE
preview does not work for wildcard searches. file cannot be loaded and a blank page is loaded instead

### ISSUE THREAD

**Issue by danilos** [richardwilly98/es-dms#17]
preview does not work for wildcard searches. file cannot be loaded and a blank page is loaded instead

if following a \* wildcard search a file is opened for preview, a window opens displaying only a blank page

**Comment by richardwilly98** [comment]
Cannot reproduce.

Please test again and provide log file if still happens.

**Comment by danilos** [comment]
yes I cannot reproduce at this time
